import { Customer, InternetPackage, User, IssueReport, ActivityLog, IspProfile, WhatsAppTemplate } from "../types";

// This file can be auto-generated by Supabase CLI in a real project
// For now, we manually define it based on our schema.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      activity_logs: {
        Row: ActivityLog
        Insert: Omit<ActivityLog, 'id'> & { id?: string }
        Update: Partial<ActivityLog>
      }
      customers: {
        Row: Customer
        Insert: Omit<Customer, 'id'> & { id?: string }
        Update: Partial<Customer>
      }
      issue_reports: {
        Row: IssueReport
        Insert: Omit<IssueReport, 'id'> & { id?: string }
        Update: Partial<IssueReport>
      }
      isp_profile: {
        Row: IspProfile & { id: number }
        Insert: Partial<IspProfile>
        Update: Partial<IspProfile>
      }
      packages: {
        Row: InternetPackage
        Insert: InternetPackage
        Update: Partial<InternetPackage>
      }
      users: {
        Row: User
        Insert: User
        Update: Partial<User>
      }
      whatsapp_templates: {
        Row: WhatsAppTemplate
        Insert: WhatsAppTemplate
        Update: Partial<WhatsAppTemplate>
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
